create table MedStaff_Data (
	staffID INT,
	fName VARCHAR(50),
	lName VARCHAR(50),
	salary INT,
	startDate DATE,
	jobTitle VARCHAR(50)
);
insert into MedStaff_Data (staffID, fName, lName, salary, startDate, jobTitle) values (1, 'Markus', 'Skoggins', 69360, '9/16/2019', 'Medical Assistant');
insert into MedStaff_Data (staffID, fName, lName, salary, startDate, jobTitle) values (2, 'Dougy', 'Arlett', 48487, '11/24/2019', 'Physician');
insert into MedStaff_Data (staffID, fName, lName, salary, startDate, jobTitle) values (3, 'Schuyler', 'Treasure', 40571, '4/6/2020', 'Scribe');
insert into MedStaff_Data (staffID, fName, lName, salary, startDate, jobTitle) values (4, 'Jeramie', 'McCrachen', 68821, '3/19/2019', 'Physician');
insert into MedStaff_Data (staffID, fName, lName, salary, startDate, jobTitle) values (5, 'Arin', 'Knoble', 60842, '10/21/2019', 'Scribe');
insert into MedStaff_Data (staffID, fName, lName, salary, startDate, jobTitle) values (6, 'Tiffanie', 'Groarty', 57105, '4/14/2019', 'Medical Assistant');
insert into MedStaff_Data (staffID, fName, lName, salary, startDate, jobTitle) values (7, 'Brockie', 'Gulberg', 64596, '4/23/2019', 'Physician');
insert into MedStaff_Data (staffID, fName, lName, salary, startDate, jobTitle) values (8, 'Doug', 'Noraway', 40102, '3/28/2019', 'Physician');
insert into MedStaff_Data (staffID, fName, lName, salary, startDate, jobTitle) values (9, 'Dacey', 'Simacek', 78679, '12/20/2019', 'Medical Assistant');
insert into MedStaff_Data (staffID, fName, lName, salary, startDate, jobTitle) values (10, 'Sunny', 'Dallewater', 70916, '3/15/2019', 'Coordinator');
insert into MedStaff_Data (staffID, fName, lName, salary, startDate, jobTitle) values (11, 'Catlaina', 'Shenton', 91979, '8/19/2019', 'Admission Intake Clerk');
insert into MedStaff_Data (staffID, fName, lName, salary, startDate, jobTitle) values (12, 'Samantha', 'Van der Kruijs', 83336, '5/5/2019', 'Admission Intake Clerk');
insert into MedStaff_Data (staffID, fName, lName, salary, startDate, jobTitle) values (13, 'Georg', 'Mattimoe', 83562, '5/16/2019', 'Physician');
insert into MedStaff_Data (staffID, fName, lName, salary, startDate, jobTitle) values (14, 'Neron', 'Claiden', 41412, '8/1/2019', 'Coordinator');
insert into MedStaff_Data (staffID, fName, lName, salary, startDate, jobTitle) values (15, 'Bartholomeus', 'Culmer', 90198, '6/18/2020', 'Scribe');
insert into MedStaff_Data (staffID, fName, lName, salary, startDate, jobTitle) values (16, 'Gardie', 'Gunstone', 92153, '2/23/2020', 'Nurse');
insert into MedStaff_Data (staffID, fName, lName, salary, startDate, jobTitle) values (17, 'Roxana', 'Braunes', 80410, '5/10/2019', 'Nurse');
insert into MedStaff_Data (staffID, fName, lName, salary, startDate, jobTitle) values (18, 'Cynthea', 'Dewdney', 72158, '6/4/2020', 'Nurse');
insert into MedStaff_Data (staffID, fName, lName, salary, startDate, jobTitle) values (19, 'Abe', 'Cobbald', 70396, '1/22/2020', 'Coordinator');
insert into MedStaff_Data (staffID, fName, lName, salary, startDate, jobTitle) values (20, 'Bonni', 'Moakes', 47757, '10/6/2019', 'Medical Assistant');
insert into MedStaff_Data (staffID, fName, lName, salary, startDate, jobTitle) values (21, 'Min', 'Fader', 44273, '7/10/2019', 'Medical Assistant');
insert into MedStaff_Data (staffID, fName, lName, salary, startDate, jobTitle) values (22, 'Gradeigh', 'Pyper', 89444, '8/10/2020', 'Nurse');
insert into MedStaff_Data (staffID, fName, lName, salary, startDate, jobTitle) values (23, 'Tammi', 'McGeachey', 91458, '5/17/2019', 'Physician');
insert into MedStaff_Data (staffID, fName, lName, salary, startDate, jobTitle) values (24, 'Malachi', 'Bendel', 53321, '9/8/2020', 'Medical Assistant');
insert into MedStaff_Data (staffID, fName, lName, salary, startDate, jobTitle) values (25, 'Cecilio', 'Treacher', 40159, '8/9/2020', 'Nurse');
insert into MedStaff_Data (staffID, fName, lName, salary, startDate, jobTitle) values (26, 'Shayne', 'Cancelier', 45592, '8/28/2020', 'Admission Intake Clerk');
insert into MedStaff_Data (staffID, fName, lName, salary, startDate, jobTitle) values (27, 'Mathew', 'Skelhorn', 49972, '2/2/2019', 'Medical Assistant');
insert into MedStaff_Data (staffID, fName, lName, salary, startDate, jobTitle) values (28, 'Paulita', 'Doppler', 68259, '11/3/2019', 'Nurse');
insert into MedStaff_Data (staffID, fName, lName, salary, startDate, jobTitle) values (29, 'Arel', 'Fawdrey', 98023, '11/3/2019', 'Nurse');
insert into MedStaff_Data (staffID, fName, lName, salary, startDate, jobTitle) values (30, 'Jonathon', 'Iskowicz', 95477, '4/20/2019', 'Scribe');
insert into MedStaff_Data (staffID, fName, lName, salary, startDate, jobTitle) values (31, 'Aindrea', 'Boake', 84185, '1/1/2020', 'Nurse');
insert into MedStaff_Data (staffID, fName, lName, salary, startDate, jobTitle) values (32, 'Shaun', 'Corinton', 52433, '7/8/2019', 'Scribe');
insert into MedStaff_Data (staffID, fName, lName, salary, startDate, jobTitle) values (33, 'Willie', 'Pugh', 76073, '11/25/2019', 'Medical Assistant');
insert into MedStaff_Data (staffID, fName, lName, salary, startDate, jobTitle) values (34, 'Benedick', 'Philipsson', 68391, '8/8/2020', 'Admission Intake Clerk');
insert into MedStaff_Data (staffID, fName, lName, salary, startDate, jobTitle) values (35, 'Yasmin', 'Petto', 76155, '2/18/2020', 'Medical Assistant');
insert into MedStaff_Data (staffID, fName, lName, salary, startDate, jobTitle) values (36, 'Damiano', 'Scarratt', 40727, '11/27/2019', 'Physician');
insert into MedStaff_Data (staffID, fName, lName, salary, startDate, jobTitle) values (37, 'Obed', 'Colthard', 77678, '4/23/2019', 'Physician');
insert into MedStaff_Data (staffID, fName, lName, salary, startDate, jobTitle) values (38, 'Crystal', 'Pollicatt', 52464, '9/2/2019', 'Medical Assistant');
insert into MedStaff_Data (staffID, fName, lName, salary, startDate, jobTitle) values (39, 'Robby', 'Chrestien', 85628, '11/29/2019', 'Medical Assistant');
insert into MedStaff_Data (staffID, fName, lName, salary, startDate, jobTitle) values (40, 'Angie', 'Scholz', 83585, '11/7/2019', 'Medical Assistant');
insert into MedStaff_Data (staffID, fName, lName, salary, startDate, jobTitle) values (41, 'Claire', 'Wasielewicz', 40860, '6/18/2019', 'Nurse');
insert into MedStaff_Data (staffID, fName, lName, salary, startDate, jobTitle) values (42, 'Zebadiah', 'Houldin', 75103, '7/12/2020', 'Nurse');
insert into MedStaff_Data (staffID, fName, lName, salary, startDate, jobTitle) values (43, 'Kiele', 'Beneyto', 67089, '2/24/2020', 'Coordinator');
insert into MedStaff_Data (staffID, fName, lName, salary, startDate, jobTitle) values (44, 'Bianca', 'Ligoe', 81355, '6/8/2020', 'Admission Intake Clerk');
insert into MedStaff_Data (staffID, fName, lName, salary, startDate, jobTitle) values (45, 'Bertha', 'Meadley', 63675, '2/25/2020', 'Medical Assistant');
insert into MedStaff_Data (staffID, fName, lName, salary, startDate, jobTitle) values (46, 'Steffie', 'Bere', 71226, '4/6/2020', 'Coordinator');
insert into MedStaff_Data (staffID, fName, lName, salary, startDate, jobTitle) values (47, 'Erik', 'Totton', 86565, '8/20/2019', 'Scribe');
insert into MedStaff_Data (staffID, fName, lName, salary, startDate, jobTitle) values (48, 'Milli', 'Kloser', 75644, '4/12/2019', 'Physician');
insert into MedStaff_Data (staffID, fName, lName, salary, startDate, jobTitle) values (49, 'Gordy', 'Culleford', 67837, '5/31/2020', 'Nurse');
insert into MedStaff_Data (staffID, fName, lName, salary, startDate, jobTitle) values (50, 'Hamel', 'Eadmead', 45606, '6/9/2019', 'Nurse');
insert into MedStaff_Data (staffID, fName, lName, salary, startDate, jobTitle) values (51, 'Myrtia', 'Fosse', 71879, '3/19/2020', 'Physician');
insert into MedStaff_Data (staffID, fName, lName, salary, startDate, jobTitle) values (52, 'Olympie', 'Maker', 93971, '12/31/2019', 'Physician');
insert into MedStaff_Data (staffID, fName, lName, salary, startDate, jobTitle) values (53, 'Abie', 'Philcott', 90956, '4/26/2020', 'Physician');
insert into MedStaff_Data (staffID, fName, lName, salary, startDate, jobTitle) values (54, 'Sydney', 'Hambly', 79976, '6/29/2019', 'Medical Assistant');
insert into MedStaff_Data (staffID, fName, lName, salary, startDate, jobTitle) values (55, 'Alaric', 'Rendall', 59794, '7/12/2019', 'Medical Assistant');
insert into MedStaff_Data (staffID, fName, lName, salary, startDate, jobTitle) values (56, 'Theo', 'Keedwell', 53075, '3/27/2020', 'Medical Assistant');
insert into MedStaff_Data (staffID, fName, lName, salary, startDate, jobTitle) values (57, 'Carolina', 'Morgon', 78836, '2/16/2019', 'Nurse');
insert into MedStaff_Data (staffID, fName, lName, salary, startDate, jobTitle) values (58, 'Leroi', 'Lowers', 83457, '5/13/2019', 'Physician');
insert into MedStaff_Data (staffID, fName, lName, salary, startDate, jobTitle) values (59, 'Bobby', 'Poag', 84772, '4/19/2020', 'Nurse');
insert into MedStaff_Data (staffID, fName, lName, salary, startDate, jobTitle) values (60, 'Fabe', 'Sutch', 95545, '5/9/2020', 'Medical Assistant');
insert into MedStaff_Data (staffID, fName, lName, salary, startDate, jobTitle) values (61, 'Sapphire', 'Danilin', 73992, '6/3/2019', 'Nurse');
insert into MedStaff_Data (staffID, fName, lName, salary, startDate, jobTitle) values (62, 'Lawrence', 'Rens', 73400, '9/23/2019', 'Nurse');
insert into MedStaff_Data (staffID, fName, lName, salary, startDate, jobTitle) values (63, 'Paton', 'Klejna', 56666, '4/17/2019', 'Physician');
insert into MedStaff_Data (staffID, fName, lName, salary, startDate, jobTitle) values (64, 'Chrissy', 'Dives', 98900, '11/1/2019', 'Coordinator');
insert into MedStaff_Data (staffID, fName, lName, salary, startDate, jobTitle) values (65, 'Lilli', 'Lampitt', 64103, '6/10/2019', 'Medical Assistant');
insert into MedStaff_Data (staffID, fName, lName, salary, startDate, jobTitle) values (66, 'Jermaine', 'Dyhouse', 84277, '8/9/2019', 'Admission Intake Clerk');
insert into MedStaff_Data (staffID, fName, lName, salary, startDate, jobTitle) values (67, 'Starlin', 'Shoulders', 66642, '12/16/2019', 'Nurse');
insert into MedStaff_Data (staffID, fName, lName, salary, startDate, jobTitle) values (68, 'Tabatha', 'Twiname', 92187, '12/4/2019', 'Medical Assistant');
insert into MedStaff_Data (staffID, fName, lName, salary, startDate, jobTitle) values (69, 'Alysa', 'Wasmuth', 65039, '7/7/2019', 'Admission Intake Clerk');
insert into MedStaff_Data (staffID, fName, lName, salary, startDate, jobTitle) values (70, 'Flint', 'Magnar', 41863, '11/7/2019', 'Medical Assistant');
insert into MedStaff_Data (staffID, fName, lName, salary, startDate, jobTitle) values (71, 'Maxwell', 'Brok', 43495, '6/11/2019', 'Coordinator');
insert into MedStaff_Data (staffID, fName, lName, salary, startDate, jobTitle) values (72, 'Josephine', 'Freiburger', 44089, '11/4/2019', 'Admission Intake Clerk');
insert into MedStaff_Data (staffID, fName, lName, salary, startDate, jobTitle) values (73, 'Phillip', 'Vankeev', 73980, '8/25/2020', 'Medical Assistant');
insert into MedStaff_Data (staffID, fName, lName, salary, startDate, jobTitle) values (74, 'Greg', 'Snookes', 87759, '10/10/2019', 'Nurse');
insert into MedStaff_Data (staffID, fName, lName, salary, startDate, jobTitle) values (75, 'Den', 'Novik', 93672, '8/6/2020', 'Nurse');
insert into MedStaff_Data (staffID, fName, lName, salary, startDate, jobTitle) values (76, 'Tiffi', 'Lammiman', 49594, '6/24/2019', 'Scribe');
insert into MedStaff_Data (staffID, fName, lName, salary, startDate, jobTitle) values (77, 'Erik', 'Noot', 97268, '5/18/2019', 'Nurse');
insert into MedStaff_Data (staffID, fName, lName, salary, startDate, jobTitle) values (78, 'Ogden', 'Hufton', 66469, '9/9/2020', 'Admission Intake Clerk');
insert into MedStaff_Data (staffID, fName, lName, salary, startDate, jobTitle) values (79, 'Guenevere', 'Bamborough', 92909, '1/12/2020', 'Admission Intake Clerk');
insert into MedStaff_Data (staffID, fName, lName, salary, startDate, jobTitle) values (80, 'Penni', 'Wethers', 86282, '11/23/2019', 'Medical Assistant');
insert into MedStaff_Data (staffID, fName, lName, salary, startDate, jobTitle) values (81, 'Algernon', 'Zecchetti', 51071, '2/26/2019', 'Coordinator');
insert into MedStaff_Data (staffID, fName, lName, salary, startDate, jobTitle) values (82, 'Dede', 'Maplestone', 43030, '1/19/2019', 'Nurse');
insert into MedStaff_Data (staffID, fName, lName, salary, startDate, jobTitle) values (83, 'Barny', 'Danilenko', 81301, '11/14/2019', 'Nurse');
insert into MedStaff_Data (staffID, fName, lName, salary, startDate, jobTitle) values (84, 'Mirna', 'Rolingson', 62890, '10/6/2019', 'Admission Intake Clerk');
insert into MedStaff_Data (staffID, fName, lName, salary, startDate, jobTitle) values (85, 'Carma', 'Tax', 64559, '10/24/2019', 'Admission Intake Clerk');
insert into MedStaff_Data (staffID, fName, lName, salary, startDate, jobTitle) values (86, 'Philipa', 'Wrighton', 94595, '12/18/2019', 'Scribe');
insert into MedStaff_Data (staffID, fName, lName, salary, startDate, jobTitle) values (87, 'Giacomo', 'Akester', 40608, '10/16/2019', 'Medical Assistant');
insert into MedStaff_Data (staffID, fName, lName, salary, startDate, jobTitle) values (88, 'Benji', 'Coulthard', 64878, '2/9/2020', 'Nurse');
insert into MedStaff_Data (staffID, fName, lName, salary, startDate, jobTitle) values (89, 'Grover', 'Geraldi', 85948, '9/17/2019', 'Medical Assistant');
insert into MedStaff_Data (staffID, fName, lName, salary, startDate, jobTitle) values (90, 'Mic', 'Vezey', 89095, '1/9/2020', 'Medical Assistant');
insert into MedStaff_Data (staffID, fName, lName, salary, startDate, jobTitle) values (91, 'Tammara', 'Cowper', 96111, '8/26/2020', 'Admission Intake Clerk');
insert into MedStaff_Data (staffID, fName, lName, salary, startDate, jobTitle) values (92, 'Tabby', 'Serjeantson', 52354, '2/4/2019', 'Medical Assistant');
insert into MedStaff_Data (staffID, fName, lName, salary, startDate, jobTitle) values (93, 'Roderick', 'Headland', 44996, '10/20/2019', 'Scribe');
insert into MedStaff_Data (staffID, fName, lName, salary, startDate, jobTitle) values (94, 'Vernice', 'Yegorchenkov', 69279, '1/18/2019', 'Nurse');
insert into MedStaff_Data (staffID, fName, lName, salary, startDate, jobTitle) values (95, 'Kassandra', 'Dorkens', 77161, '8/19/2019', 'Medical Assistant');
insert into MedStaff_Data (staffID, fName, lName, salary, startDate, jobTitle) values (96, 'Brandi', 'Piotr', 55704, '7/25/2020', 'Coordinator');
insert into MedStaff_Data (staffID, fName, lName, salary, startDate, jobTitle) values (97, 'Orazio', 'Braune', 93594, '4/14/2019', 'Coordinator');
insert into MedStaff_Data (staffID, fName, lName, salary, startDate, jobTitle) values (98, 'Merrile', 'Corbert', 77989, '9/1/2019', 'Nurse');
insert into MedStaff_Data (staffID, fName, lName, salary, startDate, jobTitle) values (99, 'Marve', 'Page', 71222, '8/15/2020', 'Nurse');
insert into MedStaff_Data (staffID, fName, lName, salary, startDate, jobTitle) values (100, 'Herman', 'Shermore', 85700, '3/10/2020', 'Scribe');
